/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador;

/**
 *
 * @author Sebastian
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Simulador de Ampolleta");
        this.setLocationRelativeTo(Ventana.this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        spinWatts = new javax.swing.JSpinner();
        spinVolts = new javax.swing.JSpinner();
        lblWatts = new javax.swing.JLabel();
        lblVolts = new javax.swing.JLabel();
        btnON = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblAmp = new javax.swing.JLabel();
        txtAmpInte = new javax.swing.JTextField();
        lblAmpInte = new javax.swing.JLabel();
        txtAmpResi = new javax.swing.JTextField();
        lblAmpOhms = new javax.swing.JLabel();
        lblCircu = new javax.swing.JLabel();
        txtCircuInte = new javax.swing.JTextField();
        txtCircuResi = new javax.swing.JTextField();
        lblCircuInte = new javax.swing.JLabel();
        lblCircuResi = new javax.swing.JLabel();
        lblGif = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuLimpiar = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(spinWatts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, 20));
        jPanel1.add(spinVolts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, -1));

        lblWatts.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWatts.setText("WATTS");
        jPanel1.add(lblWatts, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        lblVolts.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVolts.setText("VOLTS");
        jPanel1.add(lblVolts, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        btnON.setText("ON");
        btnON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnONActionPerformed(evt);
            }
        });
        jPanel1.add(btnON, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simple.png"))); // NOI18N
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblAmp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAmp.setText("Ampolleta:");
        jPanel1.add(lblAmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        txtAmpInte.setEditable(false);
        jPanel1.add(txtAmpInte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 70, -1));

        lblAmpInte.setText("Ampere");
        jPanel1.add(lblAmpInte, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 50, 20));

        txtAmpResi.setEditable(false);
        txtAmpResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmpResiActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmpResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 70, -1));

        lblAmpOhms.setText("Ohms");
        jPanel1.add(lblAmpOhms, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 20));

        lblCircu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCircu.setText("Circuito:");
        jPanel1.add(lblCircu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        txtCircuInte.setEditable(false);
        txtCircuInte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCircuInteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCircuInte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 70, -1));

        txtCircuResi.setEditable(false);
        jPanel1.add(txtCircuResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, -1));

        lblCircuInte.setText("Ampere");
        jPanel1.add(lblCircuInte, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 20));

        lblCircuResi.setText("Ohms");
        jPanel1.add(lblCircuResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, 20));

        lblGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ampolleta.gif"))); // NOI18N
        jPanel1.add(lblGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 70, 70));

        jMenu1.setText("Archivo");

        jMenuLimpiar.setText("Limpiar");
        jMenuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLimpiarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLimpiar);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuAcercaDe.setText("Acerca de");
        jMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLimpiarActionPerformed
        // TODO add your handling code here:
        txtAmpInte.setText(null);
        txtAmpResi.setText(null);
        txtCircuInte.setText(null);
        txtCircuResi.setText(null);
    }//GEN-LAST:event_jMenuLimpiarActionPerformed

    private void txtAmpResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmpResiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmpResiActionPerformed

    private void txtCircuInteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCircuInteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCircuInteActionPerformed

    private void btnONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnONActionPerformed
        // TODO add your handling code here:
        /*
        * En este evento asignare los valores a los objetos
        * y luego los convertire a string para pasarlos al textfield.
        */
        Ampolleta ampolletaUno = new Ampolleta();
        ampolletaUno.setPotencia((Integer) spinWatts.getValue());
        Circuito circuitoUno = new Circuito();
        circuitoUno.setVoltaje((Integer) spinVolts.getValue());
        circuitoUno.setIntensidad(ampolletaUno.getPotencia());
        circuitoUno.setResistencia();
        ampolletaUno.setIntensidad(circuitoUno.getIntensidad());
        ampolletaUno.setResistencia(circuitoUno.getResistencia());
        String ampoInte = Float.toString(ampolletaUno.getIntensidad());
        String ampoResi = Float.toString(ampolletaUno.getResistencia());
        String circuInte = Float.toString(circuitoUno.getIntensidad());
        String circuResis = Float.toString(circuitoUno.getResistencia());
        txtAmpInte.setText(ampoInte);
        txtAmpResi.setText(ampoResi);
        txtCircuInte.setText(circuInte);
        txtCircuResi.setText(circuResis);
    }//GEN-LAST:event_btnONActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcercaDeActionPerformed
        // TODO add your handling code here:
        Acerca acercaDe = new Acerca(this, rootPaneCheckingEnabled);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuAcercaDeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnON;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAcercaDe;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuLimpiar;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAmp;
    private javax.swing.JLabel lblAmpInte;
    private javax.swing.JLabel lblAmpOhms;
    private javax.swing.JLabel lblCircu;
    private javax.swing.JLabel lblCircuInte;
    private javax.swing.JLabel lblCircuResi;
    private javax.swing.JLabel lblGif;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblVolts;
    private javax.swing.JLabel lblWatts;
    private javax.swing.JSpinner spinVolts;
    private javax.swing.JSpinner spinWatts;
    private javax.swing.JTextField txtAmpInte;
    private javax.swing.JTextField txtAmpResi;
    private javax.swing.JTextField txtCircuInte;
    private javax.swing.JTextField txtCircuResi;
    // End of variables declaration//GEN-END:variables
}
